# Generated by Django 5.2.6 on 2025-09-16 10:22

from django.db import migrations


def init_data(apps, schema_editor):
    RoleModel = apps.get_model('task', 'Role')
    RoleModel.objects.create(name="User")
    RoleModel.objects.create(name="Guest")
    RoleModel.objects.create(name="Admin")

class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(init_data),
    ]
